org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
systemProp.http.proxyHost=21.0.0.33
systemProp.http.proxyPort=15004
systemProp.https.proxyHost=21.0.0.33
systemProp.https.proxyPort=15004
systemProp.http.nonProxyHosts=localhost|127.0.0.1|169.254.169.254|metadata.google.internal

systemProp.http.proxyUser=container_container_01YVsYFZiCPWykPAAW4vfa86--claude_code_remote--9bdb9b
systemProp.http.proxyPassword=jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6ImNjNDU4Y2I5LWVlZTQtNGNkZS1iOTZjLTJlZTI1OTQxNTc0MSIsImlhdCI6MTc3MTYxOTczMywiZXhwIjoxNzcxNjM0MTMzLCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwiaXNfYW50X2hpcGkiOiJmYWxzZSIsInVzZV9lZ3Jlc3NfZ2F0ZXdheSI6InRydWUiLCJzZXNzaW9uX2lkIjoic2Vzc2lvbl8wMUYzenc3TThQbXZVNWZiY3ZXdXc4Q1YiLCJjb250YWluZXJfaWQiOiJjb250YWluZXJfMDFZVnNZRlppQ1BXeWtQQUFXNHZmYTg2LS1jbGF1ZGVfY29kZV9yZW1vdGUtLTliZGI5YiJ9.JPURuNHEHfzuk__-QV-KyglHrrqoEgLME0efXy_MSKMF6SQA02t2feLZ3iTAaexatH0WETPYw-JfLpK841Ce8g
systemProp.https.proxyUser=container_container_01YVsYFZiCPWykPAAW4vfa86--claude_code_remote--9bdb9b
systemProp.https.proxyPassword=jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6ImNjNDU4Y2I5LWVlZTQtNGNkZS1iOTZjLTJlZTI1OTQxNTc0MSIsImlhdCI6MTc3MTYxOTczMywiZXhwIjoxNzcxNjM0MTMzLCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwiaXNfYW50X2hpcGkiOiJmYWxzZSIsInVzZV9lZ3Jlc3NfZ2F0ZXdheSI6InRydWUiLCJzZXNzaW9uX2lkIjoic2Vzc2lvbl8wMUYzenc3TThQbXZVNWZiY3ZXdXc4Q1YiLCJjb250YWluZXJfaWQiOiJjb250YWluZXJfMDFZVnNZRlppQ1BXeWtQQUFXNHZmYTg2LS1jbGF1ZGVfY29kZV9yZW1vdGUtLTliZGI5YiJ9.JPURuNHEHfzuk__-QV-KyglHrrqoEgLME0efXy_MSKMF6SQA02t2feLZ3iTAaexatH0WETPYw-JfLpK841Ce8g
